/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ActivityLabel = IDL.Variant({
  'jumping' : IDL.Null,
  'clapping' : IDL.Null,
  'stretching' : IDL.Null,
  'walking' : IDL.Null,
  'waving' : IDL.Null,
  'sitting' : IDL.Null,
  'bending' : IDL.Null,
  'standing' : IDL.Null,
  'running' : IDL.Null,
  'smiling' : IDL.Null,
});
export const ActivityResult = IDL.Record({
  'startTime' : IDL.Float64,
  'activityLabel' : ActivityLabel,
  'endTime' : IDL.Float64,
  'confidence' : IDL.Float64,
});
export const AnalysisStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const VideoAnalysis = IDL.Record({
  'id' : IDL.Nat,
  'status' : AnalysisStatus,
  'duration' : IDL.Float64,
  'video' : ExternalBlob,
  'submittedAt' : Time,
  'submittedBy' : IDL.Principal,
  'fileSize' : IDL.Nat64,
  'filename' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
  'getActivityResults' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityResult)],
      ['query'],
    ),
  'getAllAnalyses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(VideoAnalysis)],
      ['query'],
    ),
  'getAnalysis' : IDL.Func([IDL.Nat], [VideoAnalysis], ['query']),
  'setActivityResults' : IDL.Func([IDL.Nat, IDL.Vec(ActivityResult)], [], []),
  'submitVideo' : IDL.Func(
      [IDL.Text, IDL.Nat64, IDL.Float64, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'updateAnalysisStatus' : IDL.Func([IDL.Nat, AnalysisStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ActivityLabel = IDL.Variant({
    'jumping' : IDL.Null,
    'clapping' : IDL.Null,
    'stretching' : IDL.Null,
    'walking' : IDL.Null,
    'waving' : IDL.Null,
    'sitting' : IDL.Null,
    'bending' : IDL.Null,
    'standing' : IDL.Null,
    'running' : IDL.Null,
    'smiling' : IDL.Null,
  });
  const ActivityResult = IDL.Record({
    'startTime' : IDL.Float64,
    'activityLabel' : ActivityLabel,
    'endTime' : IDL.Float64,
    'confidence' : IDL.Float64,
  });
  const AnalysisStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const VideoAnalysis = IDL.Record({
    'id' : IDL.Nat,
    'status' : AnalysisStatus,
    'duration' : IDL.Float64,
    'video' : ExternalBlob,
    'submittedAt' : Time,
    'submittedBy' : IDL.Principal,
    'fileSize' : IDL.Nat64,
    'filename' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteAnalysis' : IDL.Func([IDL.Nat], [], []),
    'getActivityResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityResult)],
        ['query'],
      ),
    'getAllAnalyses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(VideoAnalysis)],
        ['query'],
      ),
    'getAnalysis' : IDL.Func([IDL.Nat], [VideoAnalysis], ['query']),
    'setActivityResults' : IDL.Func([IDL.Nat, IDL.Vec(ActivityResult)], [], []),
    'submitVideo' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Float64, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'updateAnalysisStatus' : IDL.Func([IDL.Nat, AnalysisStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };