/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLabel = { 'jumping' : null } |
  { 'clapping' : null } |
  { 'stretching' : null } |
  { 'walking' : null } |
  { 'waving' : null } |
  { 'sitting' : null } |
  { 'bending' : null } |
  { 'standing' : null } |
  { 'running' : null } |
  { 'smiling' : null };
export interface ActivityResult {
  'startTime' : number,
  'activityLabel' : ActivityLabel,
  'endTime' : number,
  'confidence' : number,
}
export type AnalysisStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface VideoAnalysis {
  'id' : bigint,
  'status' : AnalysisStatus,
  'duration' : number,
  'video' : ExternalBlob,
  'submittedAt' : Time,
  'submittedBy' : Principal,
  'fileSize' : bigint,
  'filename' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'deleteAnalysis' : ActorMethod<[bigint], undefined>,
  'getActivityResults' : ActorMethod<[bigint], Array<ActivityResult>>,
  'getAllAnalyses' : ActorMethod<[bigint, bigint], Array<VideoAnalysis>>,
  'getAnalysis' : ActorMethod<[bigint], VideoAnalysis>,
  'setActivityResults' : ActorMethod<
    [bigint, Array<ActivityResult>],
    undefined
  >,
  'submitVideo' : ActorMethod<[string, bigint, number, ExternalBlob], bigint>,
  'updateAnalysisStatus' : ActorMethod<[bigint, AnalysisStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];