/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActivityResult {
    id: bigint;
    startTime: number;
    activityLabel: ActivityLabel;
    endTime: number;
    analysisId: bigint;
    confidence: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VideoAnalysis {
    id: bigint;
    status: AnalysisStatus;
    duration: number;
    fileBlob: ExternalBlob;
    fileSize: bigint;
    filename: string;
    uploadDate: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ActivityLabel {
    jumping = "jumping",
    clapping = "clapping",
    stretching = "stretching",
    walking = "walking",
    waving = "waving",
    sitting = "sitting",
    bending = "bending",
    standing = "standing",
    running = "running",
    smiling = "smiling"
}
export enum AnalysisStatus {
    pending = "pending",
    completed = "completed",
    processing = "processing",
    failed = "failed"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    deleteAnalysis(id: bigint): Promise<boolean>;
    getActivityResults(analysisId: bigint): Promise<Array<ActivityResult>>;
    getAllAnalyses(): Promise<Array<VideoAnalysis>>;
    getAnalysis(id: bigint): Promise<VideoAnalysis | null>;
    setActivityResults(analysisId: bigint, results: Array<ActivityResult>): Promise<boolean>;
    submitVideo(filename: string, fileSize: bigint, duration: number, fileBlob: ExternalBlob): Promise<bigint>;
    updateAnalysisStatus(id: bigint, status: AnalysisStatus): Promise<boolean>;
}
import type { ActivityLabel as _ActivityLabel, ActivityResult as _ActivityResult, AnalysisStatus as _AnalysisStatus, ExternalBlob as _ExternalBlob, VideoAnalysis as _VideoAnalysis, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async deleteAnalysis(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return result;
        }
    }
    async getActivityResults(arg0: bigint): Promise<Array<ActivityResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityResults(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityResults(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnalyses(): Promise<Array<VideoAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnalyses();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnalyses();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysis(arg0: bigint): Promise<VideoAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async setActivityResults(arg0: bigint, arg1: Array<ActivityResult>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setActivityResults(arg0, to_candid_vec_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActivityResults(arg0, to_candid_vec_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitVideo(arg0: string, arg1: bigint, arg2: number, arg3: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVideo(arg0, arg1, arg2, await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVideo(arg0, arg1, arg2, await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateAnalysisStatus(arg0: bigint, arg1: AnalysisStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnalysisStatus(arg0, to_candid_AnalysisStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnalysisStatus(arg0, to_candid_AnalysisStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityLabel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLabel): ActivityLabel {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityResult): ActivityResult {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisStatus): AnalysisStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_VideoAnalysis_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoAnalysis): Promise<VideoAnalysis> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoAnalysis]): Promise<VideoAnalysis | null> {
    return value.length === 0 ? null : await from_candid_VideoAnalysis_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: number;
    activityLabel: _ActivityLabel;
    endTime: number;
    analysisId: bigint;
    confidence: number;
}): {
    id: bigint;
    startTime: number;
    activityLabel: ActivityLabel;
    endTime: number;
    analysisId: bigint;
    confidence: number;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        activityLabel: from_candid_ActivityLabel_n11(_uploadFile, _downloadFile, value.activityLabel),
        endTime: value.endTime,
        analysisId: value.analysisId,
        confidence: value.confidence
    };
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AnalysisStatus;
    duration: number;
    fileBlob: _ExternalBlob;
    fileSize: bigint;
    filename: string;
    uploadDate: bigint;
}): Promise<{
    id: bigint;
    status: AnalysisStatus;
    duration: number;
    fileBlob: ExternalBlob;
    fileSize: bigint;
    filename: string;
    uploadDate: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_AnalysisStatus_n16(_uploadFile, _downloadFile, value.status),
        duration: value.duration,
        fileBlob: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.fileBlob),
        fileSize: value.fileSize,
        filename: value.filename,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jumping: null;
} | {
    clapping: null;
} | {
    stretching: null;
} | {
    walking: null;
} | {
    waving: null;
} | {
    sitting: null;
} | {
    bending: null;
} | {
    standing: null;
} | {
    running: null;
} | {
    smiling: null;
}): ActivityLabel {
    return "jumping" in value ? ActivityLabel.jumping : "clapping" in value ? ActivityLabel.clapping : "stretching" in value ? ActivityLabel.stretching : "walking" in value ? ActivityLabel.walking : "waving" in value ? ActivityLabel.waving : "sitting" in value ? ActivityLabel.sitting : "bending" in value ? ActivityLabel.bending : "standing" in value ? ActivityLabel.standing : "running" in value ? ActivityLabel.running : "smiling" in value ? ActivityLabel.smiling : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
}): AnalysisStatus {
    return "pending" in value ? AnalysisStatus.pending : "completed" in value ? AnalysisStatus.completed : "processing" in value ? AnalysisStatus.processing : "failed" in value ? AnalysisStatus.failed : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoAnalysis>): Promise<Array<VideoAnalysis>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoAnalysis_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityResult>): Array<ActivityResult> {
    return value.map((x)=>from_candid_ActivityResult_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLabel_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLabel): _ActivityLabel {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityResult): _ActivityResult {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_AnalysisStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisStatus): _AnalysisStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: number;
    activityLabel: ActivityLabel;
    endTime: number;
    analysisId: bigint;
    confidence: number;
}): {
    id: bigint;
    startTime: number;
    activityLabel: _ActivityLabel;
    endTime: number;
    analysisId: bigint;
    confidence: number;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        activityLabel: to_candid_ActivityLabel_n23(_uploadFile, _downloadFile, value.activityLabel),
        endTime: value.endTime,
        analysisId: value.analysisId,
        confidence: value.confidence
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLabel): {
    jumping: null;
} | {
    clapping: null;
} | {
    stretching: null;
} | {
    walking: null;
} | {
    waving: null;
} | {
    sitting: null;
} | {
    bending: null;
} | {
    standing: null;
} | {
    running: null;
} | {
    smiling: null;
} {
    return value == ActivityLabel.jumping ? {
        jumping: null
    } : value == ActivityLabel.clapping ? {
        clapping: null
    } : value == ActivityLabel.stretching ? {
        stretching: null
    } : value == ActivityLabel.walking ? {
        walking: null
    } : value == ActivityLabel.waving ? {
        waving: null
    } : value == ActivityLabel.sitting ? {
        sitting: null
    } : value == ActivityLabel.bending ? {
        bending: null
    } : value == ActivityLabel.standing ? {
        standing: null
    } : value == ActivityLabel.running ? {
        running: null
    } : value == ActivityLabel.smiling ? {
        smiling: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisStatus): {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} | {
    failed: null;
} {
    return value == AnalysisStatus.pending ? {
        pending: null
    } : value == AnalysisStatus.completed ? {
        completed: null
    } : value == AnalysisStatus.processing ? {
        processing: null
    } : value == AnalysisStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ActivityResult>): Array<_ActivityResult> {
    return value.map((x)=>to_candid_ActivityResult_n21(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
